### ISSUE TITLE
example to render into OpenGL?

### ISSUE THREAD

**Issue by sk8245** [3d0c/gmf#117]
Hello,
Can you please provide some example to render a video with sound into OpenGL? Would be appreciated
Thanks

**Comment by 3d0c** [comment]
Hi. This example is to complex and just an overkill.

But you can start with following examples:
[OpenGL-Video-Player](https://github.com/Golim4r/OpenGL-Video-Player/tree/master/src)
Take a look at this line [Renderer.cpp#L346](https://github.com/Golim4r/OpenGL-Video-Player/blob/master/src/Renderer.cpp#L346)

You can refer to [video-to-image.go](https://github.com/3d0c/gmf/blob/master/examples/video-to-image.go) or [video-to-goImage.go](https://github.com/3d0c/gmf/blob/master/examples/video-to-goImage.go) to get an idea of how to obtaining frame data in RGB format.
Pretty the same with audio.

You can just port the core stuff of OpenGL-Video-Player in [go-gl](https://github.com/go-gl) and combine it with gmf for getting frames.
