### ISSUE TITLE
go.mod incorrect cannot download module

### ISSUE THREAD

**Issue by gokalper** [3d0c/gmf#154]
A recent [fix](https://github.com/3d0c/gmf/pull/153/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6) for ffmpeg 5.1 support merged the go.mod from another fork. Go will not download the module as it references the incorrect repo - github.com/reijnenhhfm/gmf

```
go get github.com/3d0c/gmf
go: downloading github.com/3d0c/gmf v0.0.0-20220906003747-3c1e70196c59
go: github.com/3d0c/gmf@v0.0.0-20220906003747-3c1e70196c59: parsing go.mod:
        module declares its path as: github.com/reijnenhhfm/gmf
                but was required as: github.com/3d0c/gmf
```

current go.mod:
```
module github.com/reijnenhhfm/gmf

go 1.12

require github.com/stretchr/testify v1.7.1
```

**Comment by gokalper** [comment]
created [PR](https://github.com/3d0c/gmf/pull/155) to fix this:

**Comment by 3d0c** [comment]
Merged
