### ISSUE TITLE
Looks like frame doesn't provide access to Audio data buffers

### ISSUE THREAD

**Issue by gaffo** [3d0c/gmf#33]
Would you be amenable to this. I'd like to be able to pull Audio with this.

**Comment by baadc0de** [comment]
@gaffo how did you solve this eventually? Running into the same problem.

**Comment by 3d0c** [comment]
@baadc0de frame now has GetRawFrame() method, which returns AVFrame struct. You can access it directly.

**Comment by baadc0de** [comment]
@3d0c  I'm new to CGO but I'm getting 

`(cannot refer to unexported field or method data)`

When I try to access the `data` field of the `struct_AVFrame` from my code when linking your lib. I'm using vgo modules.

**Comment by 3d0c** [comment]
Supposed usage of this method is following:

```go
package xxx

/*

void process_raw_data(uint8_t** data, int* nb_samples) {
        // do something with raw samples here
}

*/
import "C"

func main() {
	...

	// Get raw pointer to AVFrame
	avFrame := (*C.struct_AVFrame)(unsafe.Pointer(frame.GetRawFrame()))

	// Run you C code
        C.process_raw_data(
                (**C.uint8_t)(unsafe.Pointer(&avFrame.data)),
		(*_Ctype_int)(unsafe.Pointer(&avFrame.nb_samples)),
        )
       
        ...
}
```

**Comment by baadc0de** [comment]
Even with the code above I did not get it to work outside of the gmf project (so as a separate module that is using the gmf module). However, in my fork of gmf, I have added this method:

```go
func (f *Frame) GetRawAudioData(plane int) []byte {
	return C.GoBytes(unsafe.Pointer(f.avFrame.data[plane]), C.int(f.LineSize(plane)))
}
```

Which compiles, but I did not try it out yet. So in short, I can access `data` inside gmf source code but not in my app.

**Comment by 3d0c** [comment]
I've tested your code and it works fine.
