### ISSUE TITLE
How to call ffmpeg code without losing quality?

### ISSUE THREAD

**Issue by seaguest** [3d0c/gmf#43]
Hello,

I am getting a problem when I use gmf, the audio of output video has a lot of noises, how can I call ffmpeg by code  which does exactly same thing as "ffmpeg -i mv.webm  -acodec aac -vcodec libx264  mv1.mp4"?

Here is my post in stackoverflow, could anyone help?

http://stackoverflow.com/questions/37085959/how-to-call-ffmpeg-code-without-losing-quality

best regards

**Comment by 3d0c** [comment]
@seaguest will try to find some time to solve your problem

**Comment by seaguest** [comment]
@3d0c 

Thank you for your reply.

It looks like some packets of input stream are lost in the output stream, it seems both video and audio have this problem, but the audio loss is much more obvious.

The command line works fine, from the log, they have the same setting, I guess the way here with gmf we call libav* library is a little different than going though ffmpeg.c, maybe it has something to do with time base and time stamp or ...

I am looking at the problem too, but I am very new to ffmpeg, do you have any idea what would be the problem? Could you give me some hint?

best regards
