### ISSUE TITLE
Go - Cross Compilation for ARM

### ISSUE THREAD

**Issue by minhajakhterkhan199** [3d0c/gmf#57]
Everything working fine with amd64 but when we are compiling it for arm, after setting GOARCH=arm, it is giving it below error, please advise how to solve it

src/Manager/MediaManager.go:28: undefined: FmtCtx
src/MediaManager.go:28: undefined: Stream
src/Manager/MediaManager.go:29: undefined: CodecCtx
src/Manager/MediaManager.go:30: undefined: Stream
src/Manager/MediaManager.go:32: undefined: FindEncoder
src/Manager/MediaManager.go:32: undefined: Codec
src/Manager/MediaManager.go:40: undefined: NewCodecCtx
src/Manager/MediaManager.go:46: undefined: CODEC_FLAG_GLOBAL_HEADER
src/Manager/MediaManager.go:50: undefined: FF_COMPLIANCE_EXPERIMENTAL
src/Manager/MediaManager.go:53: undefined: AVMEDIA_TYPE_AUDIO

Regards,

**Comment by minhajakhterkhan199** [comment]
Kindly respond on above query

**Comment by 3d0c** [comment]
@minhajakhterkhan199 Hello. I suppose that's because CGO doesn't support cross compilation. You have to build it on the target platform.

**Comment by minhajakhterkhan199** [comment]
Before compilation I am seeting CGO_ENABLED and it gives me gcc: error: unrecognized command line option '-marm'
Please advise how to solve this issue.

**Comment by 3d0c** [comment]
You have to build your app on the target platform and you don't need to add any flags. Just do `go get` for `gmf` and then `go build` for your app.

**Comment by minhajakhterkhan199** [comment]
After resetting everything & cloning a new gmf. For amd64 compilation, we are getting below error. Please advise how to issue
GOROOT=/usr/local/go
GOPATH=/home/minhaj/GoLang
/usr/local/go/bin/go build -o /home/minhaj/GoLang/bin/GoLangRun /home/minhaj/GoLang/src/IndoorMass/IndoorMain.go
# pkg-config --cflags libavutil libavformat libavcodec libavcodec libavutil libavcodec libavutil libavformat libavdevice libavcodec libavutil libavcodec libavutil libavutil libavcodec libavutil libavformat libswresample libswscale libavcodec libavutil
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavdevice was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavdevice.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavdevice' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libswresample was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswresample.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswresample' found
Package libswscale was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswscale.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswscale' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
pkg-config: exit status 1

-------------------------------------------------------------------------------------------------------
For arm compilation we are getting below error
-------------------------------------------------------------------------------------------------------
minhaj@minhaj-VirtualBox:~/GoLang$ go build -v IndoorMass/
runtime/internal/sys
runtime/internal/atomic
runtime
errors
internal/race
sync/atomic
unicode
sync
io
unicode/utf8
encoding
bytes
math
bufio
syscall
strconv
encoding/base64
reflect
time
os
strings
fmt
sort
unicode/utf16
image/color
image
encoding/json
flag
golang.org/x/image/math/fixed
image/internal/imageutil
encoding/binary
image/draw
log
github.com/golang/freetype/raster
golang.org/x/image/font
github.com/icza/mjpeg
github.com/skip2/go-qrcode/bitset
github.com/skip2/go-qrcode/reedsolomon
github.com/golang/freetype/truetype
image/jpeg
path/filepath
io/ioutil
github.com/skip2/go-qrcode
compress/flate
IndoorMass/General
hash
hash/crc32
github.com/3d0c/gmf
github.com/kaey/framebuffer
compress/gzip
hash/adler32
compress/zlib
container/list
image/png
context
crypto/subtle
crypto/cipher
internal/syscall/unix
math/rand
crypto/aes
crypto
math/big
crypto/des
crypto/sha512
crypto/hmac
crypto/internal/cipherhw
crypto/md5
crypto/rc4
crypto/sha1
crypto/sha256
encoding/hex
encoding/pem
internal/nettrace
internal/singleflight
net
crypto/rand
crypto/elliptic
encoding/asn1
crypto/ecdsa
crypto/rsa
crypto/dsa
crypto/x509/pkix
vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20
vendor/golang_org/x/crypto/poly1305
vendor/golang_org/x/crypto/chacha20poly1305
vendor/golang_org/x/crypto/curve25519
crypto/x509
vendor/golang_org/x/net/http2/hpack
vendor/golang_org/x/net/idna
vendor/golang_org/x/net/lex/httplex
vendor/golang_org/x/text/transform
vendor/golang_org/x/text/unicode/norm
crypto/tls
vendor/golang_org/x/text/width
mime
mime/quotedprintable
net/textproto
mime/multipart
net/http/httptrace
net/http/internal
net/url
path
runtime/debug
net/http
IndoorMass/Manager
# IndoorMass/Manager
src/IndoorMass/Manager/MediaManager.go:125: undefined: FmtCtx
src/IndoorMass/Manager/MediaManager.go:125: undefined: Stream
src/IndoorMass/Manager/MediaManager.go:126: undefined: CodecCtx
src/IndoorMass/Manager/MediaManager.go:127: undefined: Stream
src/IndoorMass/Manager/MediaManager.go:129: undefined: FindEncoder
src/IndoorMass/Manager/MediaManager.go:129: undefined: Codec
src/IndoorMass/Manager/MediaManager.go:137: undefined: NewCodecCtx
src/IndoorMass/Manager/MediaManager.go:143: undefined: CODEC_FLAG_GLOBAL_HEADER
src/IndoorMass/Manager/MediaManager.go:147: undefined: FF_COMPLIANCE_EXPERIMENTAL
src/IndoorMass/Manager/MediaManager.go:150: undefined: AVMEDIA_TYPE_AUDIO
src/IndoorMass/Manager/MediaManager.go:150: too many errors

**Comment by minhajakhterkhan199** [comment]
Waiting for your response

**Comment by 3d0c** [comment]
@minhajakhterkhan199 Ok, let's start small: following command shall return valid path, e.g. (for my setup):

```sh
~/go/src/github.com/3d0c/gmf (master*) » pkg-config --cflags libavutil libavformat libavcodec libavcodec libavutil libavcodec libavutil libavformat libavdevice libavcodec libavutil libavcodec libavutil libavutil libavcodec libavutil libavformat libswresample libswscale libavcodec libavutil
# returns
-I/usr/local/ffmpeg/include
```

Please check `PKG_CONFIG_PATH`, it shall include `ffmpeg`'s pkgconfig, e.g.:

```sh
$ env | grep -i pkg_config
# should return something like
PKG_CONFIG_PATH=/usr/local/ffmpeg/lib/pkgconfig
```
if it isn't exist, create it with `export PKG_CONFIG_PATH=/your/path/to/ffmpeg/pkgconfig`

Surely, this folder shall contain valid `.pc` files for each library, if it doesn't, build ffmpeg from source.

But it doesn't solve your second problem (weird undefined errors), cause it needs for cgo compilation and linking. Your main problem still looks like you're trying to build gmf with different target and current platform. Please add and provide result for following command`uname -a; [your go build]`

**Comment by minhajakhterkhan199** [comment]
For amd64 it compiled & run successfully but for arm it is throwing error. Please go through below details 
 
Below command is returning a valid path as expected 
minhaj@minhaj-VirtualBox:~/GoLang$ pkg-config --cflags libavutil libavformat libavcodec libavcodec libavutil libavcodec libavutil libavformat libavdevice libavcodec libavutil libavcodec libavutil libavutil libavcodec libavutil libavformat libswresample libswscale libavcodec libavutil
-I/usr/local/ffmpeg/include

env | grep -i pkg_config was not showing anything, so I set path using below commands
minhaj@minhaj-VirtualBox:~/GoLang$ export PKG_CONFIG_PATH=/usr/local/ffmpeg/lib/pkgconfig
minhaj@minhaj-VirtualBox:~/GoLang$ env | grep -i pkg_config
PKG_CONFIG_PATH=/usr/local/ffmpeg/lib/pkgconfig

minhaj@minhaj-VirtualBox:/usr/local/ffmpeg/lib/pkgconfig$ ls -lh
total 28K
-rw-r--r-- 1 root root 367 Apr 26 18:03 libavcodec.pc
-rw-r--r-- 1 root root 477 Apr 26 18:03 libavdevice.pc
-rw-r--r-- 1 root root 458 Apr 26 18:03 libavfilter.pc
-rw-r--r-- 1 root root 405 Apr 26 18:03 libavformat.pc
-rw-r--r-- 1 root root 281 Apr 26 18:03 libavutil.pc
-rw-r--r-- 1 root root 318 Apr 26 18:03 libswresample.pc
-rw-r--r-- 1 root root 311 Apr 26 18:03 libswscale.pc



 uname -a is giving below result
minhaj@minhaj-VirtualBox:~/GoLang$ uname -a
Linux minhaj-VirtualBox 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

--------------------------------------------------------------
## **Go build for amd64, now it compiled and run sucessfully**

GOROOT=/usr/local/go
GOPATH=/home/minhaj/GoLang
/usr/local/go/bin/go build -o /home/minhaj/GoLang/bin/GoLangRun /home/minhaj/GoLang/src/IndoorMass/IndoorMain.go
# github.com/3d0c/gmf
cgo-gcc-prolog: In function ‘_cgo_e1ea90aebbbc_Cfunc_avcodec_encode_audio2’:
cgo-gcc-prolog:197:2: warning: ‘avcodec_encode_audio2’ is deprecated [-Wdeprecated-declarations]
In file included from src/github.com/3d0c/gmf/frame.go:7:0:
/usr/local/ffmpeg/include/libavcodec/avcodec.h:5385:5: note: declared here
 int avcodec_encode_audio2(AVCodecContext *avctx, AVPacket *avpkt,
     ^
cgo-gcc-prolog: In function ‘_cgo_e1ea90aebbbc_Cfunc_avcodec_encode_video2’:
cgo-gcc-prolog:218:2: warning: ‘avcodec_encode_video2’ is deprecated [-Wdeprecated-declarations]
In file included from src/github.com/3d0c/gmf/frame.go:7:0:
/usr/local/ffmpeg/include/libavcodec/avcodec.h:5424:5: note: declared here
 int avcodec_encode_video2(AVCodecContext *avctx, AVPacket *avpkt,
     ^
# github.com/3d0c/gmf
cgo-gcc-prolog: In function ‘_cgo_e1ea90aebbbc_Cfunc_avcodec_decode_audio4’:
cgo-gcc-prolog:87:2: warning: ‘avcodec_decode_audio4’ is deprecated [-Wdeprecated-declarations]
In file included from src/github.com/3d0c/gmf/packet.go:7:0:
/usr/local/ffmpeg/include/libavcodec/avcodec.h:4860:5: note: declared here
 int avcodec_decode_audio4(AVCodecContext *avctx, AVFrame *frame,
     ^
cgo-gcc-prolog: In function ‘_cgo_e1ea90aebbbc_Cfunc_avcodec_decode_video2’:
cgo-gcc-prolog:108:2: warning: ‘avcodec_decode_video2’ is deprecated [-Wdeprecated-declarations]
In file included from src/github.com/3d0c/gmf/packet.go:7:0:
/usr/local/ffmpeg/include/libavcodec/avcodec.h:4909:5: note: declared here
 int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
     ^
# github.com/3d0c/gmf
cgo-gcc-prolog: In function ‘_cgo_e1ea90aebbbc_Cfunc_avcodec_copy_context’:
cgo-gcc-prolog:42:2: warning: ‘avcodec_copy_context’ is deprecated [-Wdeprecated-declarations]
In file included from /usr/local/ffmpeg/include/libavformat/avformat.h:319:0,
                 from src/github.com/3d0c/gmf/stream.go:7:
/usr/local/ffmpeg/include/libavcodec/avcodec.h:4334:5: note: declared here
 int avcodec_copy_context(AVCodecContext *dest, const AVCodecContext *src);
     ^
/home/minhaj/GoLang/bin/GoLangRun
Simple transcoder, it guesses source format and codecs and tries to convert it to v:mpeg4/a:mp2.
usage: [input filename] [output.mp4]
MediaManagerMain_1 

2017/05/02 10:00:15 Start IndoorMass 
2017/05/02 10:00:15 Start MediaManagerMain 

MediaManagerMain_2 

MediaManagerMain_3 

MediaManagerMain_4 

MediaManagerMain_4.1 

[mp4 @ 0x24126c0] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[mp4 @ 0x24126c0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mp4 @ 0x24126c0] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[mp4 @ 0x24126c0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
2017/05/02 10:00:49 MediaManager.go:302: End MediaManagerMain 

2017/05/02 10:00:49 IndoorMain.go:42: Job Finished



-----------------------------------------------------------------------------
## **go build for arm** 
-----------------------------------------------------------------------------

GOROOT=/usr/local/go
GOPATH=/home/minhaj/GoLang
/usr/local/go/bin/go build -o /home/minhaj/GoLang/bin/GoLangRun /home/minhaj/GoLang/src/IndoorMass/IndoorMain.go
# IndoorMass/Manager
src/IndoorMass/Manager/MediaManager.go:118: undefined: FmtCtx
src/IndoorMass/Manager/MediaManager.go:118: undefined: Stream
src/IndoorMass/Manager/MediaManager.go:119: undefined: CodecCtx
src/IndoorMass/Manager/MediaManager.go:120: undefined: Stream
src/IndoorMass/Manager/MediaManager.go:122: undefined: FindEncoder
src/IndoorMass/Manager/MediaManager.go:122: undefined: Codec
src/IndoorMass/Manager/MediaManager.go:130: undefined: NewCodecCtx
src/IndoorMass/Manager/MediaManager.go:136: undefined: CODEC_FLAG_GLOBAL_HEADER
src/IndoorMass/Manager/MediaManager.go:140: undefined: FF_COMPLIANCE_EXPERIMENTAL
src/IndoorMass/Manager/MediaManager.go:143: undefined: AVMEDIA_TYPE_AUDIO
src/IndoorMass/Manager/MediaManager.go:143: too many errors

Waiting for your response.

**Comment by minhajakhterkhan199** [comment]
After setting export CC=arm-linux-gnueabi-gcc & CGO_ENABLED=1, I am getting below error... Please advise to solve the issue.

# github.com/3d0c/gmf
cgo-gcc-prolog: In function ‘_cgo_e1ea90aebbbc_Cfunc_avcodec_encode_audio2’:
cgo-gcc-prolog:194:2: warning: ‘avcodec_encode_audio2’ is deprecated [-Wdeprecated-declarations]
In file included from src/github.com/3d0c/gmf/frame.go:7:0:
/usr/local/ffmpeg/include/libavcodec/avcodec.h:5385:5: note: declared here
 int avcodec_encode_audio2(AVCodecContext *avctx, AVPacket *avpkt,
     ^
cgo-gcc-prolog: In function ‘_cgo_e1ea90aebbbc_Cfunc_avcodec_encode_video2’:
cgo-gcc-prolog:214:2: warning: ‘avcodec_encode_video2’ is deprecated [-Wdeprecated-declarations]
In file included from src/github.com/3d0c/gmf/frame.go:7:0:
/usr/local/ffmpeg/include/libavcodec/avcodec.h:5424:5: note: declared here
 int avcodec_encode_video2(AVCodecContext *avctx, AVPacket *avpkt,
     ^
# github.com/3d0c/gmf
cgo-gcc-prolog: In function ‘_cgo_e1ea90aebbbc_Cfunc_avcodec_decode_audio4’:
cgo-gcc-prolog:85:2: warning: ‘avcodec_decode_audio4’ is deprecated [-Wdeprecated-declarations]
In file included from src/github.com/3d0c/gmf/packet.go:7:0:
/usr/local/ffmpeg/include/libavcodec/avcodec.h:4860:5: note: declared here
 int avcodec_decode_audio4(AVCodecContext *avctx, AVFrame *frame,
     ^
cgo-gcc-prolog: In function ‘_cgo_e1ea90aebbbc_Cfunc_avcodec_decode_video2’:
cgo-gcc-prolog:105:2: warning: ‘avcodec_decode_video2’ is deprecated [-Wdeprecated-declarations]
In file included from src/github.com/3d0c/gmf/packet.go:7:0:
/usr/local/ffmpeg/include/libavcodec/avcodec.h:4909:5: note: declared here
 int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
     ^
# github.com/3d0c/gmf
cgo-gcc-prolog: In function ‘_cgo_e1ea90aebbbc_Cfunc_avcodec_copy_context’:
cgo-gcc-prolog:41:2: warning: ‘avcodec_copy_context’ is deprecated [-Wdeprecated-declarations]
In file included from /usr/local/ffmpeg/include/libavformat/avformat.h:319:0,
                 from src/github.com/3d0c/gmf/stream.go:7:
/usr/local/ffmpeg/include/libavcodec/avcodec.h:4334:5: note: declared here
 int avcodec_copy_context(AVCodecContext *dest, const AVCodecContext *src);
     ^
# github.com/3d0c/gmf
/usr/local/ffmpeg/lib/libavdevice.so: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status

**Comment by minhajakhterkhan199** [comment]
Waiting for your response.

**Comment by minhajakhterkhan199** [comment]
waiting for your response

**Comment by 3d0c** [comment]
Ok, i've successfully installed ffmpeg and gmf on ARM64 powered server.

```sh
~ uname -a; 
Linux scw-a7288d 4.9.23-std-1 #1 SMP Mon Apr 24 13:18:14 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
~ go build transcode.go
~ file transcode
transcode: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=57dbf7b72683eb4844b8559835feb69a26891a55, not stripped
```

So i can commit that the library works just fine (except some warnings about deprecated stuff).  

About your problem — please pay attention to my previous comment: You can not use cross compilation for sources that use CGO! You have to build CGO sources on the target platform.
