### ISSUE TITLE
Running in Docker container

### ISSUE THREAD

**Issue by lennycampino** [3d0c/gmf#78]
Is there any example to implement this library with FFmpeg in a application which runs on a Docker environment?

**Comment by 3d0c** [comment]
May be it helps — https://github.com/denismakogon/ffmpeg-debian

**Comment by ergoz** [comment]
You can try my container: riftbit/ffalpine

Here example running: https://hub.docker.com/r/riftbit/ffalpine

**Comment by ergoz** [comment]
You can try my container: riftbit/ffalpine
There are two tags: for runtime and for build

Here example running: https://hub.docker.com/r/riftbit/ffalpine
