### ISSUE TITLE
Demo/example Request

### ISSUE THREAD

**Issue by Albinzr** [3d0c/gmf#87]
Can you add an example of creating video from array of images?

**Comment by Albinzr** [comment]
Cool thanks...

**Comment by Albinzr** [comment]
Is there a way to pipe images in memory directly rather than specifying the location of the image for converting to video?

**Comment by 3d0c** [comment]
@Albinzr Yes, there is — an algorithm is something like — create empty frame, setup it up, set data with your image data, convert to YUV or different colour space if it needs, set pts, rescale to timebase, encode, write.
I'll try to write an example within this week.
