### ISSUE TITLE
Examples need to be updated

### ISSUE THREAD

**Issue by Ruxton** [3d0c/gmf#99]
Recent changes at https://github.com/3d0c/gmf/commit/220eb915323f31fb788de80dfba6cef244ac1a29 has broken most of the examples.

**Comment by 3d0c** [comment]
Hi. Yes. Please pay attention at examples/README.md.

For now only the following examples work and supported:
- video-to-image.go
- video-to-goImage.go
- images-to-video.go
- watermark.go
- mp4s-to-flv.go

I will port others ASAP.
